import { SocialMediaType } from "@linkbase/prisma/client";

export const socialMediaDisplayNames: Record<SocialMediaType, string> = {
  [SocialMediaType.EMAIL]: "Email",
  [SocialMediaType.PHONE]: "Phone",
  [SocialMediaType.INSTAGRAM]: "Instagram",
  [SocialMediaType.FACEBOOK]: "Facebook",
  [SocialMediaType.TWITTER]: "Twitter/X",
  [SocialMediaType.TIKTOK]: "TikTok",
  [SocialMediaType.LINKEDIN]: "LinkedIn",
  [SocialMediaType.YOUTUBE]: "YouTube",
  [SocialMediaType.SNAPCHAT]: "Snapchat",
  [SocialMediaType.PINTEREST]: "Pinterest",
  [SocialMediaType.REDDIT]: "Reddit",
  [SocialMediaType.TWITCH]: "Twitch",
  [SocialMediaType.GITHUB]: "GitHub",
  [SocialMediaType.BEHANCE]: "Behance",
  [SocialMediaType.DRIBBBLE]: "Dribbble",
  [SocialMediaType.MEDIUM]: "Medium",
  [SocialMediaType.SUBSTACK]: "Substack",
  [SocialMediaType.SPOTIFY]: "Spotify",
  [SocialMediaType.SOUNDCLOUD]: "SoundCloud",
  [SocialMediaType.BANDCAMP]: "Bandcamp",
  [SocialMediaType.THREADS]: "Threads",
  [SocialMediaType.MASTODON]: "Mastodon",
  [SocialMediaType.BLUESKY]: "Bluesky",
  [SocialMediaType.TUMBLR]: "Tumblr",
  [SocialMediaType.FLICKR]: "Flickr",
  [SocialMediaType.VIMEO]: "Vimeo",
};
