import { social_media_type } from "@linkbase/prisma/client/enums";

export const socialMediaDisplayNames: Record<social_media_type, string> = {
  [social_media_type.EMAIL]: "Email",
  [social_media_type.PHONE]: "Phone",
  [social_media_type.INSTAGRAM]: "Instagram",
  [social_media_type.FACEBOOK]: "Facebook",
  [social_media_type.TWITTER]: "Twitter/X",
  [social_media_type.TIKTOK]: "TikTok",
  [social_media_type.LINKEDIN]: "LinkedIn",
  [social_media_type.YOUTUBE]: "YouTube",
  [social_media_type.SNAPCHAT]: "Snapchat",
  [social_media_type.PINTEREST]: "Pinterest",
  [social_media_type.REDDIT]: "Reddit",
  [social_media_type.TWITCH]: "Twitch",
  [social_media_type.GITHUB]: "GitHub",
  [social_media_type.BEHANCE]: "Behance",
  [social_media_type.DRIBBBLE]: "Dribbble",
  [social_media_type.MEDIUM]: "Medium",
  [social_media_type.SUBSTACK]: "Substack",
  [social_media_type.SPOTIFY]: "Spotify",
  [social_media_type.SOUNDCLOUD]: "SoundCloud",
  [social_media_type.BANDCAMP]: "Bandcamp",
  [social_media_type.THREADS]: "Threads",
  [social_media_type.MASTODON]: "Mastodon",
  [social_media_type.BLUESKY]: "Bluesky",
  [social_media_type.TUMBLR]: "Tumblr",
  [social_media_type.FLICKR]: "Flickr",
  [social_media_type.VIMEO]: "Vimeo",
};
