name: Build and Deploy backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Define SSH connection details once at job level
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REMOTE_DIR: ${{ secrets.REMOTE_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install all workspace project deps
        run: pnpm install

      - name: Build Docker image
        run: |
          cd backend
          docker build -t linkbase-backend:latest -f Dockerfile ..
          docker save linkbase-backend:latest > linkbase-backend.tar

      - name: Create environment file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > backend/.env.production

      - name: Upload Docker image and deployment files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          source: "backend/linkbase-backend.tar,backend/docker-compose.yml,backend/.env.production"
          target: ${{ env.REMOTE_DIR }}
          strip_components: 1

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            cd ${{ env.REMOTE_DIR }}
            
            # Load the new Docker image
            docker load < linkbase-backend.tar
            
            # Stop and remove existing container if it exists
            docker compose down || true
            
            # Remove the old image to save space (optional)
            docker image prune -f
            
            # Start the new container with environment variables
            docker compose --env-file .env.production up -d
            
            # Clean up the tar file
            rm -f linkbase-backend.tar
            
            # Show container status
            docker compose ps
      
